spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chathura123?createDatabaseIfNotExist=true
    username: root
    password: 1qaz2wsx@
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      
